---
- name: HCP Vault Integration Example
  hosts: localhost
  tasks:
  # Gets secret value
    - name: Display the secret with HashiCorp Vault Secret Lookup & Single Secret Credential
      ansible.builtin.debug:
        msg: "{{ single_secret }}"
