---
- name: HCP Vault Integration Example
  hosts: localhost
  tasks:
  # Gets secret value
    - name: Lookup with hashi_vault
      ansible.builtin.set_fact:
        secret_1: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/ansible/test:lookup_toppings') }}"

    - name: Display the secret with hashi_vault
      ansible.builtin.debug:
        msg: "{{ secret_1 }}"

# Gets secret value and metadata
    - name: Lookup with vault_kv2_get
      ansible.builtin.set_fact:
        secret_2: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/test') }}"

    - name: Display the secret with vault_kv2_get
      ansible.builtin.debug:
        msg: "{{ secret_2 }}"
